# Generated by Django 4.0 on 2022-01-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='manga',
            new_name='manga_title',
        ),
    ]
